services:
  triton:
    image: nvcr.io/nvidia/tritonserver:23.02-py3
    container_name: triton
    ports:
      - "8000:8000"  # HTTP
      - "8001:8001"  # gRPC
      - "8002:8002"  # Metrics
    volumes:
      - ./models:/models
    command: ["tritonserver", "--model-repository=/models"]
  fastapi:
    build: ./app
    ports:
      - "8500:8500"
    container_name: fastapi
    restart: unless-stopped

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    depends_on:
      - triton

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3100:3000"
    volumes:
      - grafana-storage:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - prometheus

volumes:
  grafana-storage: